#!/bin/bash 

set -e

npm install

# docker login ghcr.io -u <GITHUB_USERNAME> -p <GITHUB_ACCESS_TOKEN> 
# Or,
# echo <GIT_TOKEN> | docker login ghcr.io -u <GIT_USERNAME> --password-stdin
docker login ghcr.io -u $1 -p $2