FROM ghcr.io/curol/devcontainers/debian:latest

LABEL org.opencontainers.image.source "https://github.com/curol/devcontainers"
LABEL org.opencontainers.image.description "Debian development environment with docker."