FROM ghcr.io/curol/devcontainers/js-pnpm:latest

LABEL org.opencontainers.image.source "https://github.com/curol/devcontainers"
LABEL org.opencontainers.image.description "Golang development environment."